In [1]:
import pandas as pd 
import numpy as np
import matplotlib as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv(r"C:\Users\hp\Downloads\homeprices (1).csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math
median_bedrooms=math.floor(df.bedrooms.median())

In [5]:
median_bedrooms

4

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Again fit makes your model learn, while predict only applies what the model has learned. Thus it makes little sense to use predict before fit.

When talking about a LinearRegressor, the fit method is the one who will determine the values of the coefficients a and b in the equation y = ax + b of the regressor, according to the training data. Once you have these coefficients, you can use the equation to predict the y value for any x. And if you want to have an idea on it's performance, you'll try x values for which you know the y values (i.e. data in the training set).

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [19]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.0018654043

In [18]:
reg.predict([[3000,3,40]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.0018654043

498408.2515740243

In [22]:
reg.predict([[2500,4,5]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [23]:
!pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5583 sha256=4e5e5bdf5d8ec6cb8bae8207a8dc3af056d6add2de58a4df1c1e19f576eb0552
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number



[notice] A new release of pip is available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
df=pd.read_csv(r"C:\Users\hp\Downloads\hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [30]:
from word2number import w2n
df['experience'] = df['experience'].fillna('zero')
df.experience = df.experience.apply(w2n.word_to_num)

In [31]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [33]:
import math
median_test_score=math.floor(df[['test_score(out of 10)']].median())

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [39]:
df[['test_score(out of 10)']]=df[['test_score(out of 10)']].fillna(median_test_score)

In [40]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [42]:
reg2=linear_model.LinearRegression()

In [46]:
reg2.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])

LinearRegression()

In [48]:
reg2.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [50]:
reg.intercept_

array([17737.26346434])

In [51]:
reg.predict([[2,9,6]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53205.96797671]])

In [52]:
reg.predict([[12,10,10]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[92002.18340611]])